---
  - name: install apache
    apt: name=apache2 state=present
  - name: Copy across new virtial hosts
    template:
      src=virtual-hosts.conf.j2
      dest=/etc/apache2/sites-available/vagrant.conf
  - name: Remove default virtual hosts
    file:
      path=/etc/apache2/sites-enabled/000-default.conf
      state=absent
    notify:
     - reload apache
  - name: Enable new vagrant virtual hosts
    file:
      src=/etc/apache2/sites-available/vagrant.conf
      dest=/etc/apache2/sites-enabled/vagrant.conf
      state=link
    notify:
     - reload apache
  - name: copy php_info from local machine to remote
    copy:
      src: /var/www/php_files/phpinfo.php
      dest: /vagrant
      owner: vagrant
      group: vagrant
      mode: 0775
