---
  - name: install python and setup tools
    apt: name=python2.7  state=present
    apt: name=python-pip state=present


  - name: install virtualenv
    pip:
      name: virtualenv
      state: present

  - set_fact:
      tar_file_name: "{{ package_name }}-{{ replicator_version }}.tar.gz"
      wheels_file_name: "{{ package_name }}-{{ replicator_version }}-py2.py3-none-any.whl"


  - name: Upload setup.py to folder
    copy:
      src: "{{ local_dist_src }}{{ tar_file_name }}"
      dest: "/tmp/{{ tar_file_name }}"
      mode: 775

  - name: Initiate virtualenv and install app
    unarchive:
      src: "/tmp/{{ tar_file_name }}"
      dest: /
      # remote_src: True
      copy: no


  - name: Upload wheels to folder
    copy:
      src: "{{ local_dist_src }}{{ wheels_file_name }}"
      dest: "/{{ package_name }}-{{ replicator_version }}/{{ wheels_file_name }}"
      mode: 775

      # state: present


  - name: install 3rd party libraries
    pip:
      requirements: "/{{ package_name }}-{{ replicator_version }}/requirements.txt"
      virtualenv: "/{{ package_name }}-{{ replicator_version }}/venv"
      state: present

  - name: setup MySQL_RabbitMQ_replicator
    shell:
      cmd: |
        source "/{{ package_name }}-{{ replicator_version }}/venv/bin/activate"
        sudo python "/{{ package_name }}-{{ replicator_version }}/setup.py" install
